name: Set Environment Variable
on:
  push:
    branches: [ main ]

jobs:
  set-env-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variable
        run: |
          echo "export GOOGLE_API_CREDENTIALS=$GOOGLE_API_CREDENTIALS" >> $GITHUB_ENV
