name: Save Secret to Environment Variable

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      run: |
        git checkout ${{ github.ref }}
        git fetch --prune --unshallow

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set up environment variable
      run: |
        echo "GOOGLE_API_CREDENTIALS=${{ secrets.GOOGLE_API_CREDENTIALS }}" >> $GITHUB_ENV

    - name: Run Python script
      run: |
        python myscript.py
      env:
        GOOGLE_API_CREDENTIALS: ${{ env.GOOGLE_API_CREDENTIALS }}
