name: Set Environment Variable
on:
  push:
    branches: [ main ]

jobs:
  set-env-variable:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variable
        env:
          GOOGLE_API_CREDENTIALS: ${{ secrets.GOOGLE_API_CREDENTIALS }}
        run: echo "GOOGLE_API_CREDENTIALS=$GOOGLE_API_CREDENTIALS" >> $GITHUB_ENV
