name: Set environment variable from secret

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variable
        env:
          MY_SECRET: ${{ secrets.GOOGLE_API_CREDENTIALS }}
        run: |
          python scripts.py

