name: Save Secret to Environment Variable

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: execute py script # email-from-python.py
            env: 
              GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
            run: python scripts.py
